# SonarQube Project Configuration
sonar.projectKey=samsteeven_taskmanager
sonar.organization=samsteeven
sonar.host.url=https://sonarcloud.io
sonar.projectName=taskmanager
sonar.projectVersion=1.0.0

# Path to source and test directories
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# Coverage configuration (JaCoCo)
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Encoding
sonar.sourceEncoding=UTF-8

# Exclusions (optional but recommended)
sonar.exclusions=src/main/java/org/demo/taskmanager/dto/**,src/main/java/org/demo/taskmanager/model/**
