# SonarQube Project Configuration
sonar.projectKey=taskmanager
sonar.projectName=TaskManagerAPI
sonar.projectVersion=0.0.1-SNAPSHOT

# Path to source and test directories
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

# Coverage configuration (JaCoCo)
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Encoding
sonar.sourceEncoding=UTF-8

# Exclusions (optional but recommended)
sonar.exclusions=src/main/java/org/demo/taskmanager/dto/**,src/main/java/org/demo/taskmanager/model/**
